Document: protontricks
Title: Debian protontricks Manual
Author: <insert document author here>
Abstract: This manual describes what protontricks is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/protontricks/protontricks.sgml.gz

Format: postscript
Files: /usr/share/doc/protontricks/protontricks.ps.gz

Format: text
Files: /usr/share/doc/protontricks/protontricks.text.gz

Format: HTML
Index: /usr/share/doc/protontricks/html/index.html
Files: /usr/share/doc/protontricks/html/*.html
